mall_app/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mall_app.users.urls')),
                  path('parking/', include('mall_app.parking.urls')),
                  path('cinema/', include('mall_app.cinema.urls')),
                  path('stores/', include('mall_app.stores.urls')),
                  path('404/', TemplateView.as_view(template_name="404.html")),
              ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mall_app/cinema/models.py
from django.contrib.auth import get_user_model
from django.db import models
from mall_app.users.models import UserProfile


# Defines a cinema hall with a name and seating capacity
class CinemaHall(models.Model):
    hall_name = models.CharField(max_length=255)
    capacity = models.IntegerField()

    class Meta:
        verbose_name_plural = "Halls"

    def __str__(self):
        return self.hall_name


# Defines a movie with its name, type, duration, and associated cinema halls
class Movie(models.Model):
    movie_name = models.CharField(max_length=255)
    movie_type = models.CharField(max_length=255)
    duration = models.DurationField()
    halls = models.ManyToManyField(CinemaHall)
    image = models.ImageField(upload_to='movies/', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Movies"

    def __str__(self):
        return self.movie_name


# Defines the schedule for a particular movie in a cinema hall
class Schedule(models.Model):
    hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    show_time = models.DateTimeField()

    class Meta:
        verbose_name_plural = "Schedules"

    def __str__(self):
        return f"{self.movie.movie_name} in {self.hall.hall_name} at {self.show_time}"


# Defines the seats in a cinema hall
class HallSeat(models.Model):
    User = get_user_model()
    hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE)
    row = models.PositiveIntegerField()
    column = models.PositiveIntegerField()
    taken = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    is_booked = models.BooleanField(default=False)

    class Meta:
        unique_together = ['row', 'column','hall']

    def __str__(self):
        return f'Hall {self.hall_id}, Row {self.row}, Column {self.column}'


# Defines a ticket purchased by a customer for a particular screening
class Ticket(models.Model):
    customer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    seat = models.ForeignKey(HallSeat, on_delete=models.CASCADE)
    screening = models.ForeignKey(Schedule, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Tickets"

    def __str__(self):
        return f"Ticket {self.id} for {self.customer.user.email}"

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>MALL</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'styles.css' %}" />
	</head>
	<body>

		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Logo -->
{#									<h1><a href="index.html" id="logo">{{ request.user }}</a></h1>#}


								<!-- Nav -->
									<nav id="nav-special">
                                    <a href="{% url 'index' %}" id="logo"><img id="logo-image" src="{% static 'images/logo.jpg'%}" alt="logo"></a>
										<a href="{% url 'index' %}">Home</a>
										<a href="{% url 'cinema_schedule' %}">Cinema</a>
										<a href="{% url 'store_list' %}">Stores</a>
                                        <a href="{% url 'parking' %}">Parking</a>
                                        {% if user.is_authenticated %}

                                            <a href="{% url 'profile' %}">{{ user.get_username }}</a>
                                        {% else %}
                                            <a href="{% url 'login_user' %}">Login</a>
                                        {% endif %}
									</nav>

							</div>
						</div>
					</div>

				</section>

			{% block content %}
            {% endblock %}
			<!-- Footer -->
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-8 col-12-medium">

								<!-- Links -->
{#									<section>#}
{#										<h2>Links to Important Stuff</h2>#}
{#										<div>#}
{#											<div class="row">#}
{#												<div class="col-3 col-12-small">#}
{#													<ul class="link-list last-child">#}
{#														<li><a href="#">Neque amet dapibus</a></li>#}
{#														<li><a href="#">Sed mattis quis rutrum</a></li>#}
{#														<li><a href="#">Accumsan suspendisse</a></li>#}
{#														<li><a href="#">Eu varius vitae magna</a></li>#}
{#													</ul>#}
{#												</div>#}
{#												<div class="col-3 col-12-small">#}
{#													<ul class="link-list last-child">#}
{#														<li><a href="#">Neque amet dapibus</a></li>#}
{#														<li><a href="#">Sed mattis quis rutrum</a></li>#}
{#														<li><a href="#">Accumsan suspendisse</a></li>#}
{#														<li><a href="#">Eu varius vitae magna</a></li>#}
{#													</ul>#}
{#												</div>#}
{#												<div class="col-3 col-12-small">#}
{#													<ul class="link-list last-child">#}
{#														<li><a href="#">Neque amet dapibus</a></li>#}
{#														<li><a href="#">Sed mattis quis rutrum</a></li>#}
{#														<li><a href="#">Accumsan suspendisse</a></li>#}
{#														<li><a href="#">Eu varius vitae magna</a></li>#}
{#													</ul>#}
{#												</div>#}
{#												<div class="col-3 col-12-small">#}
{#													<ul class="link-list last-child">#}
{#														<li><a href="#">Neque amet dapibus</a></li>#}
{#														<li><a href="#">Sed mattis quis rutrum</a></li>#}
{#														<li><a href="#">Accumsan suspendisse</a></li>#}
{#														<li><a href="#">Eu varius vitae magna</a></li>#}
{#													</ul>#}
{#												</div>#}
{#											</div>#}
{#										</div>#}
{#									</section>#}

							</div>
							<div class="col-4 col-12-medium imp-medium">

								<!-- Blurb -->
{#									<section>#}
{#										<h2>An Informative Text Blurb</h2>#}
{#										<p>#}
{#											Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu#}
{#											varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi,#}
{#											dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh#}
{#											lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.#}
{#										</p>#}
{#									</section>#}
							</div>
						</div>
					</div>
				</section>
				<div id="copyright">
					&copy Bozhil Gandurov</a>
				</div>

		</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>
	</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Features -->
    <section id="features">
        <div class="container-fluid">
            <div class="row">
                <div class="col-1"></div>
                <div class="col-10">
                    <div id="storeCarousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">

                            {% for store in stores %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <div class="row centered">
            <div class="col-4 store-border">
                <a href="{% url 'store_detail' pk=store.id %}">
                    <img src="{{ store.image.url }}" class="store-image d-block w-100" alt="{{ store.name }}"/>
                </a>
            </div>
        </div>
    </div>
{% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#storeCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#storeCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    </section>


    <style>
    #header h1 {
        position: unset;
        margin-top: 20px;
    }
    #logo-image{
        position: unset;
        height: 90px;
    }
.centered {
    display: flex;
    align-items: center;
    justify-content: center;
}

.store-border {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 550px;
    overflow: hidden;
}

.store-image {
    max-height: 80% !important;
    width: auto !important;
    max-width: 100% !important;
    margin: auto !important;
    display: none;!important;
}


    </style>

    <script>
    $(document).ready(function() {
        $('#storeCarousel').carousel({
            interval: false
        });
    });
</script>

{% endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% block content %}
{% load custom_filters %}
{% load static %}
<link rel="stylesheet" type="text/css" href="../static/cinema/seats.css">

    <br>

<div class="container">
    {% for movie in movies %}
        <div class="row">
            <div class="col-2">
                <img class="movie-poster" src="{% get_media_prefix %}{{ movie.image }}" />
            </div>
            <div class="movie col-7">
                <p class="movie-title">{{ movie.movie_name }}</p>
                <div class="container">
                    {% for schedule in movie.schedule_set.all %}
                        <button data-screening="{{ schedule.id }}" class="screening-btn">
                            {{ schedule.hall.hall_name }}: {{ schedule.show_time }}
                        </button>
                    {% endfor %}

                    {% for schedule in movie.schedule_set.all %}
                        <form data-screening="{{ schedule.id }}" class="seat-booking-form" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="screening" value="{{ schedule.id }}">

                            {% for seat in schedule.hall.hallseat_set.all %}
                                <label data-seat="{{ seat.row }}-{{ seat.column }}">
                                    <input type="checkbox" name="seats" value="{{ seat.id }}" {% if seat.id in booked_seats|get_item:schedule.id %}disabled{% endif %}>
                                </label>
                            {% endfor %}
                            <button type="submit">Book Selected Seats</button>
                        </form>
                    {% endfor %}
                </div>
            </div>
        </div>
        <hr>
    {% endfor %}
</div>
    <script>
        function updateSeatColor(label) {
            const input = label.querySelector('input');
            if (input.checked || input.disabled) {
                label.style['background-color'] = 'red';
            } else {
                label.style['background-color'] = 'green';
            }
        }

        document.querySelectorAll('.seat-booking-form label').forEach((label) => {
            const input = label.querySelector('input');
            updateSeatColor(label);
            input.addEventListener('change', () => {
                updateSeatColor(label);
            });
        });


            const screeningForms = document.querySelectorAll('.seat-booking-form[data-screening]');
            function showScreening(event) {
    screeningForms.forEach((form) => {
        if (form.dataset.screening === event.target.dataset.screening) {
            if (form.classList.contains('active')) {
                form.classList.remove('active');
            } else {
                form.classList.add('active');
            }
        } else {
            form.classList.remove('active');
        }
    });
}


        document.querySelectorAll('.screening-btn[data-screening]').forEach((btn) => {
            btn.onclick = showScreening;
        })
    </script>

{% endblock %}
</body>
</html>